[build]
command = "bun run build"
publish = "dist"  # or your build output directory

[build.processing.html]
pretty_urls = false

[build.environment]
BUN_VERSION = "latest"  # or specify a version

[images]
remote_images = [ "https://cms.baukasten.matthiashacksteiner.net/media/.*" ]

# [[redirects]]
#   from = "/"
#   to = "/de"
#   status = 302
#   conditions = {Language = ["de"]}



