[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[build]
command = "astro build"
base = "/"
publish = "dist"

[build.processing.html]
pretty_urls = false

[build.environment]
NODE_VERSION = "23"

[dev]
command = "astro dev"
targetPort = 4321
autoLaunch = false

[images]
remote_images = [ "https://cms.baukasten.matthiashacksteiner.net/media/.*" ]

# [[redirects]]
#   from = "/"
#   to = "/de"
#   status = 302
#   conditions = {Language = ["de"]}