[build]
command = "astro build"
base = "/"
publish = "dist"

# Register the astro-kirby-sync as a Netlify Build Plugin
[[plugins]]
package = "./plugins/astro-kirby-sync"

[build.processing.html]
pretty_urls = false  # Let Astro handle URL structure completely

[build.environment]
NODE_VERSION = "23"

# Ensure any non-trailing-slash URLs redirect to trailing slash versions
[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false
  conditions = {Path = ["!/*.*", "!/*/*/"]}

[images]
remote_images = [ "https://cms.baukasten.matthiashacksteiner.net/media/.*" ]

[dev]
  autoLaunch = false