[build]
command = "astro build"
base = "/"
publish = "dist"

[build.processing.html]
pretty_urls = false

[build.environment]
NODE_VERSION = "23"

[images]
remote_images = [ "https://cms.baukasten.matthiashacksteiner.net/media/.*" ]

[dev]
  autoLaunch = false

# Cache the sync state file and node_modules for faster builds
[build.cache]
  base = "/"
  paths = [
    ".astro-kirby-sync-state.json",
    "node_modules"
  ]
