[build]
#command = "astro build"
base = "/"
publish = "dist"

[build.processing.html]
pretty_urls = false

[build.environment]
NODE_VERSION = "21"

[dev]
command = "astro dev"
targetPort = 4321
autoLaunch = false

[[plugins]]
package = "./plugins/netlify-import-env"

[images]
remote_images = [ "https://cms.baukasten.matthiashacksteiner.net/media/.*" ]

[[redirects]]
  from = "/"
  to = "/de"
  status = 301
  force = true
