[build]
  # command = "npm run build:production"
  base = "/"
  publish = "dist"

[build.processing.html]
  pretty_urls = false

[build.environment]
  NODE_VERSION = "21"

[dev]
  command = "astro dev"
  targetPort = 4321

[images]
    remote_images = ["https://cms.baukasten.matthiashacksteiner.net/.*, http://cms.baukasten.test/.*"]