[build]
command = "astro build"
base = "/"
publish = "dist"

# Register build plugins
[[plugins]]
package = "./plugins/astro-kirby-sync"

[[plugins]]
package = "./plugins/font-downloader"

# Optimize function bundling
[functions]
node_bundler = "esbuild"
# Exclude plugin directories from SSR bundle
external_node_modules = ["chalk", "dotenv"]
included_files = ["!plugins/**"]

[build.processing.html]
pretty_urls = true

[build.environment]
NODE_VERSION = "23"

[dev]
  autoLaunch = false
[images]
remote_images = [ "https://cms.baukasten.matthiashacksteiner.net/media/.*" ]

[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
