[build]
command = "astro build"
base = "/"
publish = "dist"

# Register the astro-kirby-sync as a Netlify Build Plugin
[[plugins]]
package = "./plugins/astro-kirby-sync"

[build.processing.html]
pretty_urls = true

[build.environment]
NODE_VERSION = "23"

[images]
remote_images = [ "https://cms.baukasten.matthiashacksteiner.net/media/.*" ]

# SEO-friendly redirect: /preview without trailing slash -> /preview/ with trailing slash
[[redirects]]
from = "/preview"
to = "/preview/"
status = 301
force = false

[dev]
  autoLaunch = false