name: Semantic Versioning

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          bump_each_commit: true
          major_pattern: 'major:'
          minor_pattern: 'feat:'
          version_format: '${major}.${minor}.${patch}'

      - name: Show new version
        run: |
          echo "New version: ${{ steps.version.outputs.version }}"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: github.event_name == 'push' && steps.check_tag.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.version.outputs.version }}" \
            --title "Release v${{ steps.version.outputs.version }}" \
            --generate-notes
