name: Semantic Versioning

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          bump_each_commit: true
          major_pattern: 'major:'
          minor_pattern: 'feat:'
          patch_pattern: 'fix:'
          version_format: '${major}.${minor}.${patch}'
          # Change patterns if needed based on your commit message format

      - name: Show new version
        run: |
          echo "New version: ${{ steps.version.outputs.version }}"

      - name: Create GitHub Release
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.version.outputs.version }}" \
            --title "Release v${{ steps.version.outputs.version }}" \
            --generate-notes
